### ISSUE TITLE
No longer syncing roles

### ISSUE THREAD

**Issue by sauramel** [spirobel/discord-rolesync#1] opened 2022-07-04 01:37 UTC
Plugin was working as expected on 3 users and then stopped syncing any roles at all. Bot is ranked above every other role on the server and has all privileges

**Comment by sauramel** [comment] 2022-07-04 02:53
I was able to manually sync,does this process happen automatically on a schedule?

**Comment by spirobel** [comment] 2022-07-04 14:20
yes it happens automatically. The discord API is amazing, it streams all the events as they happen in real time via websocket. The manual sync is only there in case the server was offline and you want to sync the role change events that happened in the meantime. 

>Plugin was working as expected on 3 users and then stopped syncing any roles at all

there are two possibilities why this might have happened 
1. the discourse ui does not automatically refresh the groups page once your group membership changes. Your permissions have changed, but you need to press F5.
 2. the bot was offline for some reason (maybe installing other plugins, updating the server etc.) if that was the case press manual sync to catch up with what happened on discord in the meantime.  
 
thanks for using my plugin. In case you encounter any further issues, feel free to reopen this issue. I will close it for now. :slightly_smiling_face:  :+1:

**Closed as completed** 2022-07-04 14:26 UTC

**Comment by sauramel** [comment] 2022-07-05 07:30
Can you clarify what would happen if a user already had a role on discord prior to the bot being installed and no change was made? If this role is assigned to a group in Discourse what is the expected behaviour?
No groups appear to change at this point though some have been assigned on the Sync Discord Roles plugin page the status shows as offline and I am unable tp press sync.
![image](https://user-images.githubusercontent.com/41240630/177273608-15f49922-005f-4732-8fae-773cd4e692c6.png)
On this page as well a new one of these indicators is popping up each second (sorry I am not sure what this feature is actually called)
![image](https://user-images.githubusercontent.com/41240630/177273869-ecf9bf31-bfbb-47a5-9b6e-c71a83bf26ac.png)

**Comment by spirobel** [comment] 2022-07-05 08:15
> Can you clarify what would happen if a user already had a role on discord prior to the bot being installed and no change was made? If this role is assigned to a group in Discourse what is the expected behaviour?

the expected behavior is that once the bot is turned on and you press sync it should synchronize the roles.
Have you tried turning on the bot by pressing "start"?

**Comment by sauramel** [comment] 2022-07-05 23:46
Yes I have tried turning it on, once it switches to this offline state the
only way to get it working again is to disable the plugin and bot in
settings and re-enable

**Comment by sauramel** [comment] 2022-07-06 11:12
Is it possible that rate limiting is happening?
The bot will work as expected for a short time, after which it will no longer sync any roles and I am unable to turn it on by pressing start unless I disable the plugin + bot, re-generate the bot token through discord and then re-enable the plugin and bot

**Comment by spirobel** [comment] 2022-07-07 05:26
>Is it possible that rate limiting is happening?

maybe that is the case. It could  be that this limit is triggered during installation or update of discourse. Do you have a suggestion on how we might improve this?
does it work now for you after regenerating the tokens? 
if it works well enough we could add a warning to the readme and call it a day. If not we should find the root cause of this, which I suspect happens during some kind of background operation where the plugin is unnecessary. Do you think so too, or do you think this is a more general issue unrelated to updates, installation or background processes?

**Comment by sauramel** [comment] 2022-07-07 05:42
I don't know?
